


---
title: "mammographic"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

Data preparation--Balanced
```{r,echo=F, eval=T,cache=T, message=F,warning=F}
mmg_data <- read.table("/users/ccao/Documents/LabNotebook/RMarkDown/Curves of Balanced and Imbalanced Data/Mammographic/mammographic_masses.data",sep = ",") 
mmg_data <- mmg_data[,2:6]


mmg_data_1 <- mmg_data[mmg_data$V6 == 1,]
mmg_data_0 <- mmg_data[mmg_data$V6 == 0,]
mmg_data_blcd <- rbind(mmg_data_1[sample(nrow(mmg_data_1), 445),], mmg_data_0[sample(nrow(mmg_data_0), 445),])


mmg_blcd_xtrain_full <- mmg_data_blcd[c(1:223, 446:668), 1:4]
mmg_blcd_xtrain_m <- mmg_data_blcd[c(1:223, 446:668), 1:3]
mmg_blcd_xtrain_l <- mmg_data_blcd[c(1:223, 446:668), 1:2]
mmg_blcd_ytrain <- mmg_data_blcd[c(1:223, 446:668), 5]



mmg_blcd_xtest_full <- mmg_data_blcd[c(224:445, 669:890), 1:4]
mmg_blcd_xtest_m <- mmg_data_blcd[c(224:445, 669:890), 1:3]
mmg_blcd_xtest_l <- mmg_data_blcd[c(224:445, 669:890), 1:2]
mmg_blcd_ytest <- mmg_data_blcd[c(107:212, 319:424), 5]
                         
```

Data preparation--Imbalanced
```{r,echo=F, eval=T,cache=T, message=F,warning=F}

mmg_data_iblcd <- rbind(mmg_data_1[sample(nrow(mmg_data_1), 57),], mmg_data_0[sample(nrow(mmg_data_0), 516),])


mmg_iblcd_xtrain_full <- mmg_data_iblcd[c(1:29, 58:315), 1:4]
mmg_iblcd_xtrain_m <- mmg_data_iblcd[c(1:29, 58:315), 1:3]
mmg_iblcd_xtrain_l <- mmg_data_iblcd[c(1:29, 58:315), 1:2]
mmg_iblcd_ytrain <- mmg_data_iblcd[c(1:29, 58:315), 5]



mmg_iblcd_xtest_full <- mmg_data_iblcd[c(230:57, 316:573), 1:4]
mmg_iblcd_xtest_m <- mmg_data_iblcd[c(230:57, 316:573), 1:3]
mmg_iblcd_xtest_l <- mmg_data_iblcd[c(230:57, 316:573), 1:2]
mmg_iblcd_ytest <- mmg_data_iblcd[c(230:57, 316:573), 5]
```

\textcolor{blue}{Function--LASSO}
```{r,echo=F, eval=T,cache=T, message=F,warning=F}
library(glmnet)
library(ROCR)
library(ggplot2)
metrics <- function (trainx, trainy, testx, testy)
{
# fit in model  
cv <- cv.glmnet(x = trainx, y = trainy, family = "binomial", alpha = 1, nfolds = 10, type.measure = "class")
# optimal lambda from 10-fold cross-validation by lasso
lamstd = cv$lambda.min

fit <- glmnet(x = trainx, y = trainy, family = "binomial", alpha = 1)

std_probtest <- predict(fit, testx, type="response", s=lamstd)
std_predresp <- prediction(std_probtest, testy)

# ROC curve
perf_std <- performance(std_predresp, measure = "tpr", x.measure = "fpr")
# TPR
tpr <- attr(perf_std, "y.values")[[1]]
# FPR
fpr <- attr(perf_std, "x.values")[[1]]
# PR curve
perf_std <- performance(std_predresp, measure = "prec", x.measure = "rec")
# precision
precision <- attr(perf_std, "y.values")[[1]]
# recall
recall <- attr(perf_std, "x.values")[[1]]
# mcc-f1
perf_std <- performance(std_predresp, measure = "mat", x.measure = "f")
# mcc
mcc <- attr(perf_std, "y.values")[[1]]
# normalised mcc: [-1, 1] to [0, 1]
mcc.nor <- (mcc + 1)/2
# f score
f <- attr(perf_std, "x.values")[[1]]   

output <-cbind.data.frame(tpr, fpr, precision, recall, mcc.nor, f)
  return(output)
}
```

Fit Model-Balanced
=============================
```{r,echo=F, eval=T,cache=T, message=F,warning=F}
metrics.full <- metrics(mmg_blcd_xtrain_full, mmg_blcd_ytrain, mmg_blcd_xtest_full, mmg_blcd_ytest)
metrics.m <- metrics(mmg_blcd_xtrain_m, mmg_blcd_ytrain, mmg_blcd_xtest_m, mmg_blcd_ytest)
metrics.l <- metrics(mmg_blcd_xtrain_l, mmg_blcd_ytrain, mmg_blcd_xtest_l, mmg_blcd_ytest)

```

ROC-Balanced
============
```{r,echo=F, eval=T,cache=T, message=F,warning=F}
df_comb.roc = data.frame(TPR = c(metrics.full[,1], metrics.m[,1], metrics.l[,1] ), FPR = c(metrics.full[,2], metrics.m[,2], metrics.l[,2]) , model = rep(c("FULL","MEDIUM", "LOW"), times = c(length(metrics.full[,1]), length(metrics.m[,1]), length(metrics.l[,1]))))

ggplot(df_comb.roc, aes(x=FPR, y=TPR, group=model, color = model, ymin=0, ymax=1, xmin=0, xmax=1)) + 
  geom_point(size = 0.2, shape = 21, fill="white")+
  ggtitle("ROC Curve for three different classifiers") + 
  theme(plot.title=element_text(hjust=0.5))
```
