---
title: "Implementation of Curves on Mehran's TFBS Data"
output:
  html_document: default
  word_document: default
---

```{r,echo=F, eval=T,cache=T, message=F,warning=F}
library(ROCR)
library(ggplot2)
classifier_result <- function (tfbsData){
tfbs_data <- read.csv(paste("/users/ccao/TFBS_folder/", tfbsData, sep = ""), header=T, sep="\t", row.names=1)
# sample data set
sample <- tfbs_data[sample(1:nrow(tfbs_data), 100000, replace = F),]
pred <- prediction(sample$Class.True.Probability, sample$Bound)
perf <- performance(pred, measure = "tpr", x.measure = "fpr")
tpr <- attr(perf, "y.values")[[1]]
# FPR
fpr <- attr(perf, "x.values")[[1]]
# PR curve
perf <- performance(pred, measure = "prec", x.measure = "rec")
# precision
precision <- attr(perf, "y.values")[[1]]
# recall
recall <- attr(perf, "x.values")[[1]]
# mcc-f1
perf <- performance(pred, measure = "mat", x.measure = "f")
# mcc
mcc <- attr(perf, "y.values")[[1]]
# normalised mcc: [-1, 1] to [0, 1]
mcc.nor <- (mcc + 1)/2
# f score
f <- attr(perf, "x.values")[[1]]   
# auc
auc <- attr(performance(pred, "auc"), "y.values")[[1]]

output <-cbind.data.frame(tpr, fpr, precision, recall, mcc.nor, f, auc)
  return(output)
}
```


```{r,echo=F, eval=T,cache=T, message=F,warning=F}
good_classifier1_result <- classifier_result("goodTfs/chr20_CTCF_K562_neuralnet_Stringent_K562_CTCF_posterior_prob.tsv")
good_classifier2_result <- classifier_result("goodTfs/chr20_SMC3_K562_neuralnet_Stringent_K562_SMC3_posterior_prob.tsv")
average_classifier1_result <- classifier_result("averageTfs/chr20_BACH1_K562_neuralnet_Stringent_K562_BACH1_posterior_prob.tsv")
average_classifier2_result <- classifier_result("averageTfs/chr20_FOS_K562_neuralnet_Stringent_K562_FOS_posterior_prob.tsv")
bad_classifier1_result <- classifier_result("badTfs/chr20_BRD4_K562_neuralnet_Stringent_K562_BRD4_posterior_prob.tsv")
bad_classifier2_result <- classifier_result("badTfs/chr20_RELA_K562_neuralnet_Stringent_K562_RELA_posterior_prob.tsv")

tpr_index = 1
fpr_index = 2
precision_index = 3
recall_index = 4 
mcc.nor_index = 5 
f_score_index = 6
auc_index = 7

```

ROC
============
```{r,echo=F, eval=T,cache=T, message=F,warning=F}
df_comb.roc = data.frame(TPR = c(good_classifier1_result[,tpr_index], average_classifier1_result[,tpr_index], bad_classifier1_result[,tpr_index], good_classifier2_result[,tpr_index], average_classifier2_result[,tpr_index], bad_classifier2_result[,tpr_index]), FPR = c(good_classifier1_result[,fpr_index], average_classifier1_result[,fpr_index], bad_classifier1_result[,fpr_index], good_classifier2_result[,fpr_index], average_classifier2_result[,fpr_index], bad_classifier2_result[,fpr_index]) , model = rep(c("GOOD1", "AVERAGE1", "BAD1", "GOOD2", "AVERAGE2", "BAD2"), times = c(length(good_classifier1_result[,tpr_index]), length(average_classifier1_result[,tpr_index]), length(bad_classifier1_result[,tpr_index]), length(good_classifier2_result[,tpr_index]), length(average_classifier2_result[,tpr_index]), length(bad_classifier2_result[,tpr_index]))))

ggplot(df_comb.roc, aes(x=FPR, y=TPR, group=model, color = model, ymin=0, ymax=1, xmin=0, xmax=1)) + 
  geom_point(size = 0.2, shape = 21, fill="white")+
  ggtitle("ROC Curve for six different classifiers") + 
  theme(plot.title=element_text(hjust=0.5))

print("The AUCs for GOOD1, GOOD2, AVERAGE1, AVERAGE2, BAD1, BAD2 are")
print(paste(good_classifier1_result[1,auc_index], good_classifier2_result[1,auc_index], average_classifier1_result[1,auc_index], average_classifier2_result[1,auc_index], bad_classifier1_result[1,auc_index], bad_classifier2_result[1,auc_index, ], sep = ", "))
```

PR
===========
```{r,echo=F, eval=T,cache=T, message=F,warning=F}
df_comb.pr = data.frame(Precision = c(good_classifier1_result[,precision_index], average_classifier1_result[,precision_index], bad_classifier1_result[,precision_index], good_classifier2_result[,precision_index], average_classifier2_result[,precision_index], bad_classifier2_result[,precision_index]), Recall = c(good_classifier1_result[,recall_index], average_classifier1_result[,recall_index], bad_classifier1_result[,recall_index], good_classifier2_result[,recall_index], average_classifier2_result[,recall_index], bad_classifier2_result[,recall_index]) , model = rep(c("GOOD", "AVERAGE", "BAD", "GOOD2", "AVERAGE2", "BAD2"), times = c(length(good_classifier1_result[,precision_index]), length(average_classifier1_result[,precision_index]), length(bad_classifier1_result[,precision_index]), length(good_classifier2_result[,precision_index]), length(average_classifier2_result[,precision_index]), length(bad_classifier2_result[,precision_index]))))

ggplot(df_comb.pr, aes(y=Precision, x=Recall, group=model, color = model, ymin=0, ymax=1, xmin=0, xmax=1)) + 
  geom_point(size = 0.2, shape = 21, fill="white")+
  ggtitle("PR Curve for six different classifiers") + 
  theme(plot.title=element_text(hjust=0.5))
```

MCC-F1
===============
```{r,echo=F, eval=T,cache=T, message=F,warning=F}
df_comb.mf = data.frame(MCC = c(good_classifier1_result[,mcc.nor_index], average_classifier1_result[,mcc.nor_index], bad_classifier1_result[,mcc.nor_index], good_classifier2_result[,mcc.nor_index], average_classifier2_result[,mcc.nor_index], bad_classifier2_result[,mcc.nor_index]), F_1 = c(good_classifier1_result[,f_score_index], average_classifier1_result[,f_score_index], bad_classifier1_result[,f_score_index], good_classifier2_result[,f_score_index], average_classifier2_result[,f_score_index], bad_classifier2_result[,f_score_index]) , model = rep(c("GOOD", "AVERAGE", "BAD", "GOOD2", "AVERAGE2", "BAD2"), times = c(length(good_classifier1_result[,mcc.nor_index]), length(average_classifier1_result[,mcc.nor_index]), length(bad_classifier1_result[,mcc.nor_index]), length(good_classifier2_result[,mcc.nor_index]), length(average_classifier2_result[,mcc.nor_index]), length(bad_classifier2_result[,mcc.nor_index]))))

ggplot(df_comb.mf, aes(x=F_1, y=MCC, group=model, color = model, ymin=0, ymax=1, xmin=0, xmax=1)) + 
  geom_point(size = 0.2, shape = 21, fill="white")+
  ggtitle("MCC-F1 Curve for six different classifiers") + 
  theme(plot.title=element_text(hjust=0.5))
```

MCC-Precision
======================
```{r,echo=F, eval=T,cache=T, message=F,warning=F}
df_comb.mp = data.frame(MCC = c(good_classifier1_result[,mcc.nor_index], average_classifier1_result[,mcc.nor_index], bad_classifier1_result[,mcc.nor_index], good_classifier2_result[,mcc.nor_index], average_classifier2_result[,mcc.nor_index], bad_classifier2_result[,mcc.nor_index]), Precision = c(good_classifier1_result[,precision_index], average_classifier1_result[,precision_index], bad_classifier1_result[,precision_index], good_classifier2_result[,precision_index], average_classifier2_result[,precision_index], bad_classifier2_result[,precision_index]) , model = rep(c("GOOD", "AVERAGE", "BAD", "GOOD2", "AVERAGE2", "BAD2"), times = c(length(good_classifier1_result[,mcc.nor_index]), length(average_classifier1_result[,mcc.nor_index]), length(bad_classifier1_result[,mcc.nor_index]), length(good_classifier2_result[,mcc.nor_index]), length(average_classifier2_result[,mcc.nor_index]), length(bad_classifier2_result[,mcc.nor_index]))))

ggplot(df_comb.mp, aes(x=Precision, y=MCC, group=model, color = model, ymin=0, ymax=1, xmin=0, xmax=1)) + 
  geom_point(size = 0.2, shape = 21, fill="white") +
  ggtitle("MCC-Precision Curve for six different classifiers") + 
  theme(plot.title=element_text(hjust=0.5))
```

MCC-Recall
=====================
```{r,echo=F, eval=T,cache=T, message=F,warning=F}
df_comb.mp = data.frame(MCC = c(good_classifier1_result[,mcc.nor_index], average_classifier1_result[,mcc.nor_index], bad_classifier1_result[,mcc.nor_index], good_classifier2_result[,mcc.nor_index], average_classifier2_result[,mcc.nor_index], bad_classifier2_result[,mcc.nor_index]), Recall = c(good_classifier1_result[,recall_index], average_classifier1_result[,recall_index], bad_classifier1_result[,recall_index], good_classifier2_result[,recall_index], average_classifier2_result[,recall_index], bad_classifier2_result[,recall_index]) , model = rep(c("GOOD", "AVERAGE", "BAD", "GOOD2", "AVERAGE2", "BAD2"), times = c(length(good_classifier1_result[,mcc.nor_index]), length(average_classifier1_result[,mcc.nor_index]), length(bad_classifier1_result[,mcc.nor_index]), length(good_classifier2_result[,mcc.nor_index]), length(average_classifier2_result[,mcc.nor_index]), length(bad_classifier2_result[,mcc.nor_index]))))

ggplot(df_comb.mp, aes(x=Recall, y=MCC, group=model, color = model, ymin=0, ymax=1, xmin=0, xmax=1)) + 
  geom_point(size = 0.2, shape = 21, fill="white") +
  ggtitle("MCC-Recall Curve for six different classifiers") + 
  theme(plot.title=element_text(hjust=0.5))
```

